// <auto-generated />
using System;
using BasicBudget.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasicBudget.Infrastructure.Migrations
{
    [DbContext(typeof(BasicBudgetDbContext))]
    partial class BasicBudgetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BasicBudget.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Account_AccountNumber_Unique");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Account_CreatedAt");

                    b.ToTable("accounts", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Account_Balance_Precision", "SCALE(current_balance) <= 2");
                        });
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BudgetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("budget_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Budget_IsActive");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_Budget_DateRange");

                    b.ToTable("budgets", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Budget_DateRange", "start_date < end_date");
                        });
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AlertThreshold")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("alert_threshold");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CategoryId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.HasIndex("BudgetId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_BudgetCategory_Budget_Category_Unique");

                    b.ToTable("budget_categories", "public", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetCategory_AllocatedAmount_Positive", "allocated_amount > 0");
                        });
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Category_Name");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("IX_Category_Parent");

                    b.ToTable("categories", "public");
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CategoryId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId1");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("IX_Transaction_TransactionDate");

                    b.HasIndex("AccountId", "TransactionDate")
                        .HasDatabaseName("IX_Transaction_Account_Date");

                    b.HasIndex("CategoryId", "TransactionDate")
                        .HasDatabaseName("IX_Transaction_Category_Date");

                    b.ToTable("transactions", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Amount_NonZero", "amount != 0");
                        });
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Account", b =>
                {
                    b.HasOne("BasicBudget.Domain.Entities.Budget", null)
                        .WithMany("Accounts")
                        .HasForeignKey("BudgetId");

                    b.OwnsOne("BasicBudget.Domain.ValueObjects.Money", "CurrentBalance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("current_balance");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("AccountId");

                            b1.ToTable("accounts", "public");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("CurrentBalance")
                        .IsRequired();
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("BasicBudget.Domain.Entities.Budget", "Budget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasicBudget.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicBudget.Domain.Entities.Category", null)
                        .WithMany("BudgetCategories")
                        .HasForeignKey("CategoryId1");

                    b.OwnsOne("BasicBudget.Domain.ValueObjects.Money", "AllocatedAmount", b1 =>
                        {
                            b1.Property<Guid>("BudgetCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("allocated_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("allocated_currency");

                            b1.HasKey("BudgetCategoryId");

                            b1.ToTable("budget_categories", "public");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCategoryId");
                        });

                    b.OwnsOne("BasicBudget.Domain.ValueObjects.Money", "SpentAmount", b1 =>
                        {
                            b1.Property<Guid>("BudgetCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("spent_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("spent_currency");

                            b1.HasKey("BudgetCategoryId");

                            b1.ToTable("budget_categories", "public");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCategoryId");
                        });

                    b.Navigation("AllocatedAmount")
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");

                    b.Navigation("SpentAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Category", b =>
                {
                    b.HasOne("BasicBudget.Domain.Entities.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("BasicBudget.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasicBudget.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BasicBudget.Domain.Entities.Category", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId1");

                    b.OwnsOne("BasicBudget.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transactions", "public");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Budget", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BudgetCategories");
                });

            modelBuilder.Entity("BasicBudget.Domain.Entities.Category", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("Children");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
